# Generated by Django 5.2.1 on 2026-05-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, unique=True, verbose_name='设备名称')),
                ('ip', models.GenericIPAddressField(default='1.1.1.1', unique=True, verbose_name='IP地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('snmp_ro_community', models.CharField(max_length=999, verbose_name='只读SNMP Community')),
                ('snmp_rw_community', models.CharField(blank=True, max_length=999, verbose_name='读写SNMP Community')),
                ('ssh_username', models.CharField(max_length=999, verbose_name='SSH用户名')),
                ('ssh_password', models.CharField(max_length=999, verbose_name='SSH密码')),
                ('enable_password', models.CharField(blank=True, max_length=999, verbose_name='Enable密码')),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备类型名称')),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='SNMP类型名称')),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devicecpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, default=0, verbose_name='当前CPU利用率')),
                ('record_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_usage', to='qyt_device.devicedb', verbose_name='设备')),
            ],
        ),
        migrations.AddField(
            model_name='devicedb',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='qyt_device.devicetype', verbose_name='设备类型'),
        ),
        migrations.CreateModel(
            name='DeviceSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=999, verbose_name='oid')),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicesnmp', to='qyt_device.devicetype', verbose_name='设备类型')),
                ('snmp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicesnmp', to='qyt_device.snmptype', verbose_name='SNMP类型')),
            ],
        ),
    ]
